### ISSUE TITLE
TODO recipes

### ISSUE THREAD

**Issue by mmou** [cutelab/gastrosyntheses#6]
to try:
- https://www.seriouseats.com/recipes/2010/01/the-best-chili-recipe.html

to document:
- [ ] carbonara
- [ ] https://www.koreanbapsang.com/naengmyeon-cold-noodles/
- [ ] oat milk
- [ ] cabbage soup
- [ ] deep dish pizza
- [ ] vegan chicken nuggets

- [ ] https://food52.com/recipes/76919-salted-chocolate-buckwheat-cookie
- [ ] sourdough bagels
- [ ] sourdough english muffin https://littlespoonfarm.com/sourdough-english-muffins-recipe/
- [ ] sourdough sandwich bread
- [ ] sourdough japanese milk bread
- [ ] https://www.kingarthurbaking.com/recipes/crispy-cheesy-pan-pizza-recipe
- [ ] sticky shiitake mushroom + bamboo https://www.bosh.tv/recipes/sticky-shiitake-mushrooms
- [ ] kung pao tempeh
- [ ] egg salad sandwich
- [ ] spam musubi onigirazu
- [ ] black peper tofu https://www.epicurious.com/recipes/food/views/black-pepper-tofu-365129
- [ ] sourdough dutch oven pancake
- [ ] https://thewoksoflife.com/spicy-cold-tofu-liangban-dofu/
- [ ] https://thewoksoflife.com/ants-climbing-a-tree/
- [ ] https://fullofplants.com/tempeh-khao-soi/
- [ ] gochujang tempeh (?)
- [ ] https://thewoksoflife.com/dry-pot-cauliflower/ w/ chili oil
- [ ] chili oil recipe
